### ISSUE TITLE
In branch continuous_testing, Map_Generator.py. about FlatlandObserver and FlatlandEnv

### ISSUE THREAD

**Issue by 544211707** [marmotlab/PRIMAL2#4]
`from FlatlandEnv import *`

`from FlatlandObserver import FlatlandObserver`
line 10 and 12

Where are the two dependencies FlatlandEnv and FlatlandObserver? Why do I always report errors? This is a custom. py file, right?

**Comment by GilesLuo** [comment]
Hi,
Thanks a lot for reporting this issue.
The two dependencies were wrongly named previously (because of our code iteration). A new version of the fix has been uploaded. Pls kindly confirm that the code works well.

Best,
Zhiyao
