### ISSUE TITLE
In branch continuous_testing, Env_Builder.py. about FlatlandObserver and FlatlandEnv 

### ISSUE THREAD

**Issue by Qiutianyun456** [marmotlab/PRIMAL2#7]
from FlatlandEnv import FlatlandEnv
from FlatlandObserver import FlatlandObserver
line 1122and 1124

Where are the two dependencies FlatlandEnv and FlatlandObserver?

**Comment by GilesLuo** [comment]
Hi @Qiutianyun456,
FlatlandEnv and FlatlandObserver are renamed by PRIMAL2_Env and PRIMAL2_Observer. Lines below line 1122 are just demo code to confirm the EnvBuilder is working. Newest commit has removed those lines to avoid confusion.
Thanks for pointing out the problem！

Best,
Zhiyao
